---
version: '2'

services:
  dockerregistry:
    image: registry:2 
    container_name: dockerregistry
    ports: 
      - '5000:5000'
    volumes: 
      - /opt/dockerregistry-storage:/var/lib/registry
    restart: always  